- name: Setup MySQL Server
  hosts: mysql_server
  become: true
  roles:
    - mysql

- name: Setup Maven Build Server
  hosts: maven_server
  become: true
  roles:
    - maven

- name: Setup Tomcat Server
  hosts: tomcat_server
  become: true
  vars:
    maven_host: "{{ groups['maven'][0] }}"
  roles:
    - java
    - deploy
