- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Download Maven
  get_url:
    url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
    dest: /tmp/maven.tar.gz

- name: Extract Maven
  unarchive:
    src: /tmp/maven.tar.gz
    dest: /opt/
    remote_src: yes

- name: Symlink Maven directory
  file:
    src: /opt/apache-maven-3.9.6
    dest: /opt/maven
    state: link

- name: Add Maven to PATH
  copy:
    dest: /etc/profile.d/maven.sh
    mode: '0755'
    content: |
      export M2_HOME=/opt/maven
      export PATH=${M2_HOME}/bin:${PATH}
