# Ensure Java is installed
- name: Check if Java is installed
  command: java -version
  register: java_version
  ignore_errors: yes

# Install Java if not installed
- name: Install Java (only if not installed)
  when: java_version.failed
  apt:
    name: openjdk-17-jdk
    state: present
