- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install PyMySQL using apt
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes


- name: Create application DB
  mysql_db:
    name: myappdb
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true

- name: Create application DB user
  mysql_user:
    name: myappuser
    password: myapppassword
    priv: 'myappdb.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true
